name: Test Java Version Bump

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/test-bump-version.yml"

jobs:
  test-bump-version:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./java
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: "maven"

      - name: Install dependencies
        run: |
          sudo apt -y -qq update
          sudo apt install -y protobuf-compiler libssl-dev pkg-config

      - name: Set git configs
        run: |
          git config user.name 'Lance Release'
          git config user.email 'lance-dev@lancedb.com'

      - name: Bump java version
        run: |
          # Get current version
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          current_version=${current_version%\%}

          # Split the version into components
          major=${current_version%%.*}
          minor=${current_version#*.}
          minor=${minor%%.*}
          patch=${current_version##*.}

          # Bump patch version
          patch=$((patch + 1))

          new_version="${major}.${minor}.${patch}"

          echo "Current version: $current_version"
          echo "New version: $new_version"

          mvn versions:set versions:commit -DnewVersion=$new_version

      - name: Dry run build
        run: |
          mvn --batch-mode -DskipTests package

      - name: Show changes
        run: |
          git diff

      - name: Discard changes
        run: |
          git reset --hard HEAD
